language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test --coverage --pep8 --flakes
  - coverage run --source=lmod_proxy setup.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: iEb+lujANK3Do+qoXh4nGBppUMYGTwV0MlmjNn/Xv2HkBM/B6EJnR5NiE3qjJRbfsI5WDbdQht3fD6y997z8ishyEwsY9pkK4aO0W6mspJD0vzN6UQVnkTJRLSaCVs13seaP51uNqQfEsRF0UcOYLqpWDlxxsY/wUflenWsq8gg=
  app:
    master: lmod-proxy-ci
  on:
    repo: mitodl/lmod_proxy
