language: python
python:
  - 2.7
install:
  # Replace this with `pip install -e .` once pylmod is in pypi
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test --coverage --pep8 --flakes
  - coverage run --source=lmod_proxy setup.py test
after_success:
  coveralls
