language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - python setup.py test --coverage --pep8 --flakes
  - coverage run --source=lmod_proxy setup.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: LYKVjLOZ3jGUF9SUiRTyBTAskZI2JKgJVgHnSsGJ163A6qwcERKGXtg0iB0yxFTx01ND2kvzH2Mnilc7M60NHxdT04f8mdLXnNIYsgdtryZ93QFwJrWhkX/C8Q++E02TGR3Y+o668t/c7fnqJ2zntvYM8xk4ZE/pvvv5e4B+/z4=
  app:
    master: lmod-proxy-ci
  on:
    repo: mitodl/lmod_proxy
